export const stocks = [
    {
        name: "COALINDIA",
        price: "430.95",
        change: "-0.75",
        percent: "-0.17%",
        isUp: false,
    },
    {
        name: "IOC",
        price: "178.21",
        change: "+2.05",
        percent: "+1.16%",
        isUp: true,
    },
    {
        name: "ONGC",
        price: "272.15",
        change: "+5.55",
        percent: "+2.08%",
        isUp: true,
    },
    {
        name: "NTPC",
        price: "366.90",
        change: "+5.00",
        percent: "+1.38%",
        isUp: true,
    },
    {
        name: "POWERGRID",
        price: "294.35",
        change: "+4.60",
        percent: "+1.59%",
        isUp: true,
    },
    {
        name: "ITC",
        price: "321.40",
        change: "-1.40",
        percent: "-0.43%",
        isUp: false,
    },
    {
        name: "WIPRO",
        price: "231.47",
        change: "+1.39",
        percent: "+0.60%",
        isUp: true,
    },
    {
        name: "SBIN",
        price: "1,144.10",
        change: "-1.90",
        percent: "-0.17%",
        isUp: false,
    },
    {
        name: "JSWSTEEL",
        price: "1,244.10",
        change: "-0.90",
        percent: "-0.07%",
        isUp: false,
    },
    {
        name: "BHARTIARTL",
        price: "2,011.30",
        change: "-26.90",
        percent: "-1.32%",
        isUp: false,
    },
    {
        name: "SBIN",
        price: "1,144.10",
        change: "-1.90",
        percent: "-0.17%",
        isUp: false,
    },
    {
        name: "JSWSTEEL",
        price: "1,244.10",
        change: "-0.90",
        percent: "-0.07%",
        isUp: false,
    },
    {
        name: "BHARTIARTL",
        price: "2,011.30",
        change: "-26.90",
        percent: "-1.32%",
        isUp: false,
    },
    {
        name: "SBIN",
        price: "1,144.10",
        change: "-1.90",
        percent: "-0.17%",
        isUp: false,
    },
    {
        name: "JSWSTEEL",
        price: "1,244.10",
        change: "-0.90",
        percent: "-0.07%",
        isUp: false,
    },
    {
        name: "BHARTIARTL",
        price: "2,011.30",
        change: "-26.90",
        percent: "-1.32%",
        isUp: false,
    },
    {
        name: "SBIN",
        price: "1,144.10",
        change: "-1.90",
        percent: "-0.17%",
        isUp: false,
    },
    {
        name: "JSWSTEEL",
        price: "1,244.10",
        change: "-0.90",
        percent: "-0.07%",
        isUp: false,
    },
    {
        name: "BHARTIARTL",
        price: "2,011.30",
        change: "-26.90",
        percent: "-1.32%",
        isUp: false,
    },
];
